layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

repository: bluetiger9/bluetiger9.github.io

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 100
  exclude:
    archived: false
    forks: false
    projects:
      v4l2loopback
      TLI4970-D050T4-Current-Sensor
      arduino-nRF5
      bluetiger9.github.io
      opencvsample
      theta-live-view-with-smart-ai
      WioLTEforArduino
    # - repo-name

element14:
  content:
    - title: NXP Layerscape® LS1046A Freeway Board - Review
      description: Road Test review of the NXP Layerscape® LS1046A Freeway Board
      link: https://www.element14.com/community/roadTestReviews/3247/l/nxp-layerscape-ls1046a-freeway-board-review
      cover_image: cover-ls1046a.png

    - title: "PYNQ-Z2 Dev Board: Python Productivity for Zynq® - Review"
      description: Road Test review of the PYNQ-Z2 Dev Board
      link: https://www.element14.com/community/roadTestReviews/3120/l/pynq-z2-dev-board-python-productivity-for-zynq-review
      cover_image: cover-pynq.png

    - title: Azure Sphere based Secure IoT Air Quality Sensing Station
      description: Air Quality Monitor based on the Avnet Azure Sphere MT3620 Starter Kit
      link: https://www.element14.com/community/groups/azuresphere/blog/2019/11/30/azure-sphere-based-air-quality-monitoring
      cover_image: cover-sphere.png

    - title: AI powered CNC Painting Machine
      description: Raspberry Pi based AI painting experiments
      link: https://www.element14.com/community/community/design-challenges/picasso/blog/2019/06/10/ai-powered-cnc-painting-machine-blog-5-experimenting-with-lithophanes
      cover_image: cover-picasso.png

    - title: Bluetooth 5 Radio SoC EVM - Review
      description: Road Test review of the ON Semi RSL10 Bluetooth Low Energy SoC
      link: https://www.element14.com/community/roadTestReviews/2958/l/bluetooth-5-radio-soc-evm-review
      cover_image: cover-rsl10.png

    - title: Integrating NFC with the NXP PN7150 - Review
      description: Road Test review of the NXP PN7150 NFC controller
      link: https://www.element14.com/community/roadTestReviews/3054/l/integrating-nfc-with-the-nxp-pn7150-review
      cover_image: cover-nxp-nfc.png

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: attila-tokes
  # mastodon: your_username
  # medium: your_username
  stackoverflow: bluetiger9
  hacksterio: bluetiger9
  element14: bluetiger9
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # youtube: your_username

topics:
  - name: Internet of Things
    web_url: https://github.com/topics/iot
    image_url: https://cdn.pixabay.com/photo/2018/04/21/02/11/iot-3337536_960_720.png

  - name: Computer Vision
    web_url: https://github.com/topics/computer-vision
    image_url: https://cdn.pixabay.com/photo/2016/12/18/11/04/eye-1915455_960_720.png

  - name: Artificial Intelligence
    web_url: https://github.com/topics/artificial-intelligence
    image_url: https://cdn.pixabay.com/photo/2018/05/08/08/46/artificial-intelligence-3382509_960_720.png

  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://upload.wikimedia.org/wikipedia/commons/d/d5/Hey_Machine_Learning_Logo.png

  - name: Field Programmable Gate Array
    web_url: https://github.com/topics/fpga
    image_url: https://emblemsbf.com/img/89802.webp

  - name: Hardware Acceleration
    web_url: https://github.com/topics/hardware-acceleration
    
  - name: BlockChain
    web_url: https://github.com/topics/blockchain
    image_url: https://upload.wikimedia.org/wikipedia/commons/7/70/Ethereum_logo.svg

  - name: Electronics
    web_url: https://github.com/topics/electronics
    image_url: https://p1.pxfuel.com/preview/694/180/1007/pcb-printed-circuit-board-electronics-components.jpg

  - name: Cloud Computing
    web_url: https://github.com/topics/cloud
    image_url: https://cdn.pixabay.com/photo/2017/01/18/17/39/cloud-computing-1990405_960_720.png

  - name: Amazon Web Services
    web_url: https://github.com/topics/aws
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/AWS_Simple_Icons_AWS_Cloud.svg/1280px-AWS_Simple_Icons_AWS_Cloud.svg.png

  - name: Azure
    web_url: https://github.com/topics/azure
    image_url: https://cdn.worldvectorlogo.com/logos/azure-1.svg

  - name: Functional Programming
    web_url: https://github.com/topics/functional-programming
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Lambda_lc.svg/2000px-Lambda_lc.svg.png

  - name: Scala
    web_url: https://github.com/topics/scala
    image_url: https://upload.wikimedia.org/wikipedia/commons/8/85/Scala_logo.png

  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://live.staticflickr.com/3897/14485179234_803e4a0f08.jpg

  - name: C++
    web_url: https://github.com/topics/cpp
    image_url: https://upload.wikimedia.org/wikipedia/commons/1/16/The_C%2B%2B_logo.svg

  - name: Python
    web_url: https://github.com/topics/pyhton
    image_url: https://storage.needpix.com/rsynced_images/language-2024210_1280.png





